#!/usr/bin/perl

# Removes everything from a file that's not between ```clojure and ```.

use 5.010;
use warnings;
use strict;

while (<>) {
    next if (($. == 1 or /\A \s* ``` \s* \z/xms) .. /\A \s* ```clojure/xms);
    print;
}
